name: PR Slack Notification

on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        env:
          TITLE: ${{ github.event.pull_request.title }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          URL: ${{ github.event.pull_request.html_url }}
          REPO: ${{ github.repository }}
          DESCRIPTION: ${{ github.event.pull_request.body }}

        run: |
          payload=$(jq -n \
            --arg title "$TITLE" \
            --arg author "$AUTHOR" \
            --arg url "$URL" \
            --arg repo "$REPO" \
            --arg desc "$DESCRIPTION" \
            '{
              text: ("🚀 *New Pull Request*\n\n" +
                     "📦 *Repository:* " + $repo + "\n" +
                     "📌 *Title:* " + $title + "\n" +
                     "👤 *Author:* " + $author + "\n\n" +
                     "📝 *Description:*\n" + ($desc // "No description") + "\n\n" +
                     "🔗 *PR Link:*\n" + $url)
            }')

          curl -X POST \
            -H "Content-type: application/json" \
            --data "$payload" \
            ${{ secrets.SLACK_WEBHOOK }}
